version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "America/Chicago"
    groups:
      python-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "deps(py)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "America/Chicago"
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "ci"

